name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    name: Test Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.19.x"
            otp: "28.x"
          - elixir: "1.20.x"
            otp: "29.x"

    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies
        run: mix deps.get

      - name: Check formatting
        run: mix format --check-formatted

      - name: Check compilation warnings
        run: mix compile --warnings-as-errors

      - name: Run tests
        run: mix test
